runtime: nodejs20

env_variables:
  NODE_ENV: "production"
  JWT_SECRET: ${JWT_SECRET}

instance_class: F1

automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 10
  target_throughput_utilization: 0.6
  max_concurrent_requests: 80

handlers:
  - url: /.*
    script: auto
    secure: always

env: standard