steps:
  # Install dependencies
  - name: 'node:20'
    entrypoint: npm
    args: ['install']
    dir: 'server'

  # Run tests (if you have any)
  # - name: 'node:20'
  #   entrypoint: npm
  #   args: ['test']
  #   dir: 'server'

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args:
      - 'app'
      - 'deploy'
      - 'app.yaml'
      - '--quiet'
    dir: 'server'

timeout: '1800s'